//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPowerMT.Models.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public int CandidateID { get; set; }
        public string CandidateName { get; set; }
        public Nullable<decimal> MobileNo { get; set; }
        public string Email { get; set; }
        public Nullable<int> SkillID { get; set; }
        public int Comm_PanelID { get; set; }
        public string Comm_Panel_Status { get; set; }
        public int Tech_PanelID { get; set; }
        public string Tech_Panel_Status { get; set; }
        public int Cultural_PanelID { get; set; }
        public string Cultural_Panel_Status { get; set; }
        public string Final_Status { get; set; }
        public string Notice_Period { get; set; }
        public string Current_Org { get; set; }
        public string Recommended_Competancy { get; set; }
    
        public virtual Panel Panel { get; set; }
        public virtual Panel Panel1 { get; set; }
    }
}
